name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Sonarqube analysis
        uses: docker://sonarsource/sonar-scanner-cli:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GA_GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.GA_SONARQUBE_TOKEN }}